{
 "title": "viz",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM `tg` WHERE type = 'error'"
    }
   ]
  },
  {
   "title": "Last errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT label AS \"Label\", datetime AS \"Datetime\" FROM `tg` WHERE type = 'error' ORDER BY datetime DESC LIMIT 15"
    }
   ]
  },
  {
   "title": "Last error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT TIMEDIFF(NOW(), MAX(datetime)) FROM `tg` WHERE type = 'error'\n"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  cpu\nFROM _usage\nORDER BY datetime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  mem\nFROM _usage\nORDER BY datetime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  disk_p\nFROM _usage\nORDER BY datetime DESC LIMIT 1"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT queue_size from history ORDER BY datetime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Queue size history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  queue_size\nFROM history\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT label as \"Label\", datetime AS \"Datetime\" FROM `tg` WHERE type = 'info' ORDER BY datetime DESC LIMIT 15"
    }
   ]
  },
  {
   "title": "Processed links",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT processed_links from history ORDER BY datetime DESC LIMIT 1"
    }
   ]
  }
 ]
}